title:              Tao Wang
email:              taowangzj@gmail.com
description:        Welcome to my homepage~
author:             Tao Wang
baseurl:            "/"

# Social Profiles
twitter_username:
github_username:    TaoWangzj
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
